# For public, HTTPS servers.
version: '2.2'

services:
  postgres:
    extends:
      file: docker-compose.backend.template.m
      service: postgres
    environment:
      - KOBO_POSTGRES_DB_SERVER_ROLE=slave

networks:
  kobo-be-network:
    driver: bridge
